// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1zIp4BoVZAgl3_rZemrGPFyZJKGsAEQc',
    appId: '1:800065756855:web:98d866f64cc00dcf977732',
    messagingSenderId: '800065756855',
    projectId: 'repo-6313b',
    authDomain: 'repo-6313b.firebaseapp.com',
    databaseURL: 'https://repo-6313b-default-rtdb.firebaseio.com',
    storageBucket: 'repo-6313b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxgxM0uhbgXM9cRxXgwuw-SGYPor-e5bk',
    appId: '1:800065756855:android:6eec938cc765f813977732',
    messagingSenderId: '800065756855',
    projectId: 'repo-6313b',
    databaseURL: 'https://repo-6313b-default-rtdb.firebaseio.com',
    storageBucket: 'repo-6313b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASBSp-fMwiQmrWlJLQSRmSflmV87OHEL0',
    appId: '1:800065756855:ios:5fecbe5111b5daf0977732',
    messagingSenderId: '800065756855',
    projectId: 'repo-6313b',
    databaseURL: 'https://repo-6313b-default-rtdb.firebaseio.com',
    storageBucket: 'repo-6313b.firebasestorage.app',
    iosBundleId: 'com.example.repo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASBSp-fMwiQmrWlJLQSRmSflmV87OHEL0',
    appId: '1:800065756855:ios:5fecbe5111b5daf0977732',
    messagingSenderId: '800065756855',
    projectId: 'repo-6313b',
    databaseURL: 'https://repo-6313b-default-rtdb.firebaseio.com',
    storageBucket: 'repo-6313b.firebasestorage.app',
    iosBundleId: 'com.example.repo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1zIp4BoVZAgl3_rZemrGPFyZJKGsAEQc',
    appId: '1:800065756855:web:97923e8252240b44977732',
    messagingSenderId: '800065756855',
    projectId: 'repo-6313b',
    authDomain: 'repo-6313b.firebaseapp.com',
    databaseURL: 'https://repo-6313b-default-rtdb.firebaseio.com',
    storageBucket: 'repo-6313b.firebasestorage.app',
  );
}
